### ISSUE TITLE
[Twig Hooks] No @= support in the configuration

### ISSUE THREAD

**Issue by jakubtobiasz** [Sylius/Stack#11]
We can access the `configuration` and `context` bags in the context (YAML configuration) with using `@=`.

Example:
```yaml
twig_hooks:
	hooks:
		'my_hook':
			template: 'my_template.html.twig'
			context:
				some_key: '@=_context.something'
```

It will retrieve the value of the `something` key from the context. The same applies for the `_configuration`.

Sometimes, we might need to access the context or configuration bag in the configuration.

```yaml
twig_hooks:
	hooks:
		'my_hook':
			template: 'my_template.html.twig'
			configuration:
				attribute:
					'channel-id': '@=_context.resource.id'
```

The goal of this issue is to reuse the logic behind the bags resolving while defining the context in the configuration declaration.
